const types = {
  SET_LOADING: 'SET_LOADING',
  SET_NETWORK: 'SET_NETWORK',
  SET_LOGINSUCESS: 'SET_LOGINSUCESS',
  SET_MUSICLIST: 'SET_MUSICLIST',
  SET_SINGER: 'SET_SINGER',
  SET_PLAYING_STATE: 'SET_PLAYING_STATE',
  SET_FULL_SCREEN: 'SET_FULL_SCREEN',
  SET_PLAYLIST: 'SET_PLAYLIST',
  SET_SEQUENCE_LIST: 'SET_SEQUENCE_LIST',
  SET_PLAY_MODE: 'SET_PLAY_MODE',
  SET_CURRENT_INDEX: 'SET_CURRENT_INDEX',
  SET_TOP_LIST: 'SET_TOP_LIST',
  SET_SEARCH_HISTORY: 'SET_SEARCH_HISTORY',
  SET_PLAY_HISTORY: 'SET_PLAY_HISTORY',
  SET_FAVORITE_LIST: 'SET_FAVORITE_LIST',
  SET_MV_FULL_SCREEN: 'SET_MV_FULL_SCREEN',
  SET_RANK: 'SET_RANK'
}
export default types
